#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const APPS_DIR = path.join(__dirname, '..', 'apps');
const README_PATH = path.join(__dirname, '..', 'README.md');

function loadApps() {
  const apps = [];

  if (!fs.existsSync(APPS_DIR)) {
    return apps;
  }

  const dirs = fs.readdirSync(APPS_DIR, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  for (const dir of dirs) {
    const yamlPath = path.join(APPS_DIR, dir, 'app.yaml');
    const logoPath = path.join(APPS_DIR, dir, 'logo.png');

    if (!fs.existsSync(yamlPath)) {
      console.warn(`Warning: No app.yaml found in ${dir}`);
      continue;
    }

    try {
      const content = fs.readFileSync(yamlPath, 'utf8');
      const app = yaml.load(content);
      app._slug = dir;
      app._hasLogo = fs.existsSync(logoPath);
      apps.push(app);
    } catch (err) {
      console.error(`Error loading ${yamlPath}: ${err.message}`);
    }
  }

  return apps;
}

function generateAppCard(app) {
  const logoUrl = app._hasLogo
    ? `./apps/${app._slug}/logo.png`
    : 'https://via.placeholder.com/64?text=App';

  const openSourceBadge = app.open_source
    ? ` [![Open Source](https://img.shields.io/badge/Open%20Source-green)](${app.open_source})`
    : '';

  const tags = app.tags.map(tag => `\`${tag}\``).join(' ');

  return `### [${app.name}](${app.url})

<img src="${logoUrl}" alt="${app.name} logo" width="64" height="64">

${app.description}

${tags}${openSourceBadge}

[Documentation](${app.docs})

---`;
}

function generateAnchor(name) {
  // GitHub-style anchor generation: lowercase, replace spaces with hyphens, remove special chars
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');
}

function generateReadme(apps) {
  const sortedApps = [...apps].sort((a, b) =>
    a.name.toLowerCase().localeCompare(b.name.toLowerCase())
  );

  // Generate table of contents
  const toc = sortedApps.map(app => {
    const anchor = generateAnchor(app.name);
    return `- [${app.name}](#${anchor})`;
  }).join('\n');

  const appCards = sortedApps.map(generateAppCard).join('\n\n');

  return `# Works with OpenRouter

A curated list of apps and tools that work with [OpenRouter](https://openrouter.ai).

<!-- DO NOT EDIT THIS FILE DIRECTLY -->
<!-- This file is auto-generated. See CONTRIBUTING.md for how to add your app. -->

## Table of Contents

${toc}

## Apps

${appCards}

## Add Your App

Want to add your app to this list? See [CONTRIBUTING.md](CONTRIBUTING.md) for instructions.

---

Powered by [OpenRouter](https://openrouter.ai)
`;
}

function main() {
  console.log('Loading apps...');
  const apps = loadApps();
  console.log(`Found ${apps.length} app(s)`);

  console.log('Generating README...');
  const readme = generateReadme(apps);

  fs.writeFileSync(README_PATH, readme);
  console.log(`README.md generated with ${apps.length} app(s)`);
}

main();
