name: "Novelcrafter"
description: "Your all-in-one writing workspace that blends a powerful world-building wiki called Codex with flexible, model-agnostic AI assistance to help authors plan, draft, and finish their novels with complete creative control."
url: "https://www.novelcrafter.com"
docs: "https://www.novelcrafter.com/help/docs/ai-connections/openrouter"
tags:
  - chat
  - creative
  - productivity
date_added: "2025-01-13"
